#!/bin/bash

set -x # to test stderr output in /var/log/killercoda

kubectl taint node controlplane node-role.kubernetes.io/control-plane:NoSchedule-

helm repo add k8spacket https://k8spacket.github.io/k8spacket-helm-chart
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update

helm install k8spacket --namespace k8spacket k8spacket/k8spacket --create-namespace

echo "bG9raToKICBlbmFibGVkOiBmYWxzZQoKcHJvbXRhaWw6CiAgZW5hYmxlZDogZmFsc2UKCmZsdWVudC1iaXQ6CiAgZW5hYmxlZDogZmFsc2UKCmdyYWZhbmE6CiAgZW5hYmxlZDogdHJ1ZQogIHNpZGVjYXI6CiAgICBkYXNoYm9hcmRzOgogICAgICBlbmFibGVkOiB0cnVlCiAgaW1hZ2U6CiAgICB0YWc6IDkuNS4xMwogIHNlcnZpY2U6CiAgICB0eXBlOiBOb2RlUG9ydAogICAgbm9kZVBvcnQ6IDMxNDAwCiAgZW52OgogICAgR0ZfSU5TVEFMTF9QTFVHSU5TOiBoYW1lZGthcmJhc2k5My1ub2RlZ3JhcGhhcGktZGF0YXNvdXJjZSxtYXJjdXNvbHNzb24tanNvbi1kYXRhc291cmNlLG1hcmN1c29sc3Nvbi1keW5hbWljdGV4dC1wYW5lbAogIGRhdGFzb3VyY2VzOgogICAgbm9kZWdyYXBoYXBpLXBsdWdpbi1kYXRhc291cmNlLnlhbWw6CiAgICAgIGFwaVZlcnNpb246IDEKICAgICAgZGF0YXNvdXJjZXM6CiAgICAgICAgLSBuYW1lOiAiTm9kZSBHcmFwaCBBUEkiCiAgICAgICAgICBqc29uRGF0YToKICAgICAgICAgICAgdXJsOiAiaHR0cDovL2s4c3BhY2tldC5rOHNwYWNrZXQuc3ZjLmNsdXN0ZXIubG9jYWw6ODA4MC9ub2RlZ3JhcGgiCiAgICAgICAgICBhY2Nlc3M6ICJwcm94eSIKICAgICAgICAgIGJhc2ljQXV0aDogZmFsc2UKICAgICAgICAgIGlzRGVmYXVsdDogZmFsc2UKICAgICAgICAgIHJlYWRPbmx5OiBmYWxzZQogICAgICAgICAgdHlwZTogImhhbWVka2FyYmFzaTkzLW5vZGVncmFwaGFwaS1kYXRhc291cmNlIgogICAgICAgICAgdHlwZUxvZ29Vcmw6ICJwdWJsaWMvcGx1Z2lucy9oYW1lZGthcmJhc2k5My1ub2RlZ3JhcGhhcGktZGF0YXNvdXJjZS9pbWcvbG9nby5zdmciCiAgICAgICAgICB0eXBlTmFtZTogIm5vZGUtZ3JhcGgtcGx1Z2luIgogICAgICAgICAgb3JnSWQ6IDEKICAgICAgICAgIHZlcnNpb246IDEKICAgIG1hcmN1c29sc3Nvbi1qc29uLWRhdGFzb3VyY2UueWFtbDoKICAgICAgYXBpVmVyc2lvbjogMQogICAgICBkYXRhc291cmNlczoKICAgICAgICAtIG5hbWU6ICJKU09OIEFQSSIKICAgICAgICAgIHVybDogImh0dHA6Ly9rOHNwYWNrZXQuazhzcGFja2V0LnN2Yy5jbHVzdGVyLmxvY2FsOjgwODAvdGxzcGFyc2VyL2FwaS9kYXRhIgogICAgICAgICAgYWNjZXNzOiAicHJveHkiCiAgICAgICAgICBiYXNpY0F1dGg6IGZhbHNlCiAgICAgICAgICBpc0RlZmF1bHQ6IGZhbHNlCiAgICAgICAgICByZWFkT25seTogZmFsc2UKICAgICAgICAgIHR5cGU6ICJtYXJjdXNvbHNzb24tanNvbi1kYXRhc291cmNlIgogICAgICAgICAgdHlwZUxvZ29Vcmw6ICJwdWJsaWMvcGx1Z2lucy9tYXJjdXNvbHNzb24tanNvbi1kYXRhc291cmNlL2ltZy9sb2dvLnN2ZyIKICAgICAgICAgIHR5cGVOYW1lOiAianNvbi1hcGktcGx1Z2luIgogICAgICAgICAgb3JnSWQ6IDEKICAgICAgICAgIHZlcnNpb246IDEKCnByb21ldGhldXM6CiAgZW5hYmxlZDogdHJ1ZQogIGt1YmUtc3RhdGUtbWV0cmljczoKICAgIHJiYWM6CiAgICAgIGNyZWF0ZTogZmFsc2UKICBhbGVydG1hbmFnZXI6CiAgICBwZXJzaXN0ZW50Vm9sdW1lOgogICAgICBlbmFibGVkOiBmYWxzZQogIHNlcnZlcjoKICAgIHNlcnZpY2U6CiAgICAgIHR5cGU6IE5vZGVQb3J0CiAgICAgIG5vZGVQb3J0OiAzMTQwMQogICAgcGVyc2lzdGVudFZvbHVtZToKICAgICAgZW5hYmxlZDogZmFsc2UKICBleHRyYVNjcmFwZUNvbmZpZ3M6IHwKICAgIC0gam9iX25hbWU6ICJrOHNwYWNrZXQtbWV0cmljcyIKICAgICAgbWV0cmljc19wYXRoOiAvbWV0cmljcwogICAgICBzY3JhcGVfaW50ZXJ2YWw6IDI1cwogICAgICBrdWJlcm5ldGVzX3NkX2NvbmZpZ3M6CiAgICAgICAgLSByb2xlOiBub2RlCiAgICAgIHJlbGFiZWxfY29uZmlnczoKICAgICAgICAtIHNvdXJjZV9sYWJlbHM6IFsgX19hZGRyZXNzX18gXQogICAgICAgICAgYWN0aW9uOiByZXBsYWNlCiAgICAgICAgICByZWdleDogKFteOl0rKTouKgogICAgICAgICAgcmVwbGFjZW1lbnQ6ICQxOjY2NzYKICAgICAgICAgIHRhcmdldF9sYWJlbDogX19hZGRyZXNzX18K" | base64 -d > promop-values.yaml
helm install promop --namespace monitoring prometheus-community/kube-prometheus-stack --create-namespace --set grafana.adminPassword=k8spacket -f ./promop-values.yaml

#kubectl -n monitoring apply --recursive -f ./dashboards

#kubectl port-forward --address 0.0.0.0 service/k8spacket 8080:8080

touch /tmp/finished